check for vpn connect job

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -162,6 +162,118 @@
 #         run: sudo pkill openconnect
 
 
+
+# working code
+
+# name: Riverside Automated Tests
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       environment:
+#         description: "Select environment"
+#         required: true
+#         type: choice
+#         options:
+#           - dev
+#           - prod
+
+# jobs:
+#   cypress-tests:
+#     runs-on: macos-latest
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         site:
+#           - harivco
+#           - rchr
+#           - rivco
+#           - rivcoed
+#           - rivcoeh
+#           - voteinfo
+#           - auditorcontroller
+#           - rivcoveterans
+#           - capriverside
+#           - countytreasurer
+#           - purchasing
+#           - supervisorchuckwashington
+#           - rivcoworkforce
+#           - rivcoyac
+#           - rivcotv
+#           - rivcoparks
+#           - rctlma
+#           - rivcodpss
+#           - rivcoemd
+#           - rivcocob
+#           - rivcocounsel
+#           - hope2home
+#           - rivcoprobation
+#           - rivcopublicdefender
+#           - qualitystartrc
+#           - rcaging
+#           - rcaluc
+#           - rccfc
+#           - rcdas
+#           - rcflood
+#           - rcfva
+#           - rchmtra
+#           - rcjcra
+#           - rctlmabuilding
+#           - rctlmace
+#           - rctlmaplanning
+#           - rctlmatrans
+#           - rcwaste
+#           - rivco4
+#           - rivcoawm
+#           - rivcoconnect
+#           - rivcoda
+#           - rivcodcss
+#           - rivcodistrict1
+#           - rivcodistrict2
+#           - rivcodistrict5
+#           - rivcofm
+#           - rivcohhpws
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+
+#       - name: Install OpenConnect
+#         run: |
+#           if ! brew install openconnect; then
+#             echo "Installation failed"
+#             exit 1
+#           fi
+
+#       - name: Disconnect from VPN
+#         run: sudo pkill openconnect || echo "No existing openconnect process"
+
+#       - name: Start VPN connection (if needed)
+#         run: |
+#           echo "Starting VPN connection for site ${{ matrix.site }}..."
+#           nohup sudo openconnect --user=VTeji --passwd-on-stdin --protocol=gp --authgroup=GP_Gateway vpn1.rivcoca.org <<< "zwt3dtw@gdm.HDB.uak" & > nohup.out 2> nohup.err < /dev/null &
+
+#       - name: Verify website is up
+#         run: |
+#           echo "Checking if the website is accessible..."
+#           WEBSITE_URL=$(jq -r ".${{ matrix.site }}.${{ github.event.inputs.environment }}" cypress/fixtures/sites.json)
+#           until curl -k "$WEBSITE_URL"; do
+#             echo "Website is not up. Retrying in 10 seconds..."
+#             sleep 10
+#           done
+#           echo "$WEBSITE_URL is up!"
+
+#       - name: Install dependencies
+#         run: npm install
+
+#       - name: Run Cypress Tests
+#         run: |
+#           echo "Running Cypress tests for ${{ matrix.site }} in ${{ github.event.inputs.environment }} environment..."
+#           npm run ${{ matrix.site }}:${{ github.event.inputs.environment }}
+
+#       - name: Disconnect from VPN
+#         run: sudo pkill openconnect
+
+
 name: Riverside Automated Tests
 
 on:
@@ -176,7 +288,32 @@ on:
           - prod
 
 jobs:
+  vpn-connect:
+    runs-on: macos-latest
+    steps:
+      - name: Install OpenConnect
+        run: |
+          if ! brew install openconnect; then
+            echo "Installation failed"
+            exit 1
+          fi
+
+      - name: Disconnect from VPN (if any)
+        run: sudo pkill openconnect || echo "No existing openconnect process"
+
+      - name: Start VPN connection
+        run: |
+          echo "Starting VPN connection..."
+          nohup sudo openconnect --user=VTeji --passwd-on-stdin --protocol=gp --authgroup=GP_Gateway vpn1.rivcoca.org <<< "zwt3dtw@gdm.HDB.uak" & > nohup.out 2> nohup.err < /dev/null &
+
+      - name: Verify VPN connection
+        run: |
+          echo "Verifying VPN connection..."
+          # Replace with an appropriate command or endpoint to verify VPN is active.
+          sleep 10
+
   cypress-tests:
+    needs: vpn-connect
     runs-on: macos-latest
     strategy:
       fail-fast: false
@@ -185,69 +322,57 @@ jobs:
           - harivco
           - rchr
           - rivco
-          # - rivcoed
-          # - rivcoeh
-          # - voteinfo
-          # - auditorcontroller
-          # - rivcoveterans
-          # - capriverside
-          # - countytreasurer
-          # - purchasing
-          # - supervisorchuckwashington
-          # - rivcoworkforce
-          # - rivcoyac
-          # - rivcotv
-          # - rivcoparks
-          # - rctlma
-          # - rivcodpss
-          # - rivcoemd
-          # - rivcocob
-          # - rivcocounsel
-          # - hope2home
-          # - rivcoprobation
-          # - rivcopublicdefender
-          # - qualitystartrc
-          # - rcaging
-          # - rcaluc
-          # - rccfc
-          # - rcdas
-          # - rcflood
-          # - rcfva
-          # - rchmtra
-          # - rcjcra
-          # - rctlmabuilding
-          # - rctlmace
-          # - rctlmaplanning
-          # - rctlmatrans
-          # - rcwaste
-          # - rivco4
-          # - rivcoawm
-          # - rivcoconnect
-          # - rivcoda
-          # - rivcodcss
-          # - rivcodistrict1
-          # - rivcodistrict2
-          # - rivcodistrict5
-          # - rivcofm
-          # - rivcohhpws
+          - rivcoed
+          - rivcoeh
+          - voteinfo
+          - auditorcontroller
+          - rivcoveterans
+          - capriverside
+          - countytreasurer
+          - purchasing
+          - supervisorchuckwashington
+          - rivcoworkforce
+          - rivcoyac
+          - rivcotv
+          - rivcoparks
+          - rctlma
+          - rivcodpss
+          - rivcoemd
+          - rivcocob
+          - rivcocounsel
+          - hope2home
+          - rivcoprobation
+          - rivcopublicdefender
+          - qualitystartrc
+          - rcaging
+          - rcaluc
+          - rccfc
+          - rcdas
+          - rcflood
+          - rcfva
+          - rchmtra
+          - rcjcra
+          - rctlmabuilding
+          - rctlmace
+          - rctlmaplanning
+          - rctlmatrans
+          - rcwaste
+          - rivco4
+          - rivcoawm
+          - rivcoconnect
+          - rivcoda
+          - rivcodcss
+          - rivcodistrict1
+          - rivcodistrict2
+          - rivcodistrict5
+          - rivcofm
+          - rivcohhpws
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Install OpenConnect
-        run: |
-          if ! brew install openconnect; then
-            echo "Installation failed"
-            exit 1
-          fi
-
-      - name: Disconnect from VPN
-        run: sudo pkill openconnect || echo "No existing openconnect process"
-
-      - name: Start VPN connection (if needed)
-        run: |
-          echo "Starting VPN connection for site ${{ matrix.site }}..."
-          nohup sudo openconnect --user=VTeji --passwd-on-stdin --protocol=gp --authgroup=GP_Gateway vpn1.rivcoca.org <<< "zwt3dtw@gdm.HDB.uak" & > nohup.out 2> nohup.err < /dev/null &
+      - name: Install dependencies
+        run: npm install
 
       - name: Verify website is up
         run: |
@@ -258,9 +383,6 @@ jobs:
             sleep 10
           done
           echo "$WEBSITE_URL is up!"
-
-      - name: Install dependencies
-        run: npm install
 
       - name: Run Cypress Tests
         run: |
